type = "javascript"
name = "walentynki"
compatibility_date = "2022-02-10"
account_id = "57ceeb0a137e79623f874055e08cde7a"
zone_id = ""
route = ""
kv_namespaces = [
	{ binding = "MESSAGES", id = "ed64a9658496490081c5fad30fff2366", preview_id = "2d0f97d041084be9b842aa1b8b4fb828" },
]
workers_dev = true

[dev]
ip = "0.0.0.0"
port = 5000
local_protocol = "http"
upstream_protocol = "https"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
