name: deploy-worker

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: deploy-worker
        steps:
            - uses: actions/checkout@v2
            - name: Deploy to Cloudflare Workers with Wrangler
              uses: cloudflare/wrangler-action@1.2.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  workingDirectory: "back"
